version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10
    working_directory: ~/repo


  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
        - v1-npm-{{ checksum "package.json" }}
        - v1-npm

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo
jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  test:
    <<: *container_config

    steps:
      - *restore_repo
      - *restore_npm_cache

      - run:
          name: install dependencies
          command: |
            npm install
            npm install semantic-release
            npm install conventional-changelog-eslint

      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - node_modules/
            - ~/.npm
            - ~/.cache

      - run: npm test

  release:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_npm_cache
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: npx semantic-release -e ./config/release.config.js --debug



workflows:
  version: 2
  test_and_release:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - release:
          requires:
            - checkout_code
            - test
          filters:
            branches:
              only:
                - master
